"""tblsnmpInfo

Revision ID: 2539545074dc
Revises: 4f10d202aae8
Create Date: 2025-04-25 10:11:34.699008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2539545074dc'
down_revision = '4f10d202aae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_snmp_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guksa_id', sa.Integer(), nullable=False),
    sa.Column('equip_id', sa.Integer(), nullable=False),
    sa.Column('equip_name', sa.String(length=100), nullable=True),
    sa.Column('equip_type', sa.String(length=100), nullable=True),
    sa.Column('snmp_ip', sa.String(length=50), nullable=True),
    sa.Column('community', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('oid1', sa.String(length=50), nullable=True),
    sa.Column('oid2', sa.String(length=50), nullable=True),
    sa.Column('oid3', sa.String(length=50), nullable=True),
    sa.Column('result_code', sa.String(length=10), nullable=True),
    sa.Column('result_msg', sa.String(length=500), nullable=True),
    sa.Column('power', sa.String(length=10), nullable=True),
    sa.Column('fading', sa.String(length=10), nullable=True),
    sa.Column('get_datetime', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equip_id'], ['tbl_equipment.id'], ),
    sa.ForeignKeyConstraint(['guksa_id'], ['tbl_guksa.guksa_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_snmp_info')
    # ### end Alembic commands ###
