"""철웅 추가 mirgate

Revision ID: 4f10d202aae8
Revises: d9989cef9a4f
Create Date: 2025-04-24 20:25:53.092436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f10d202aae8'
down_revision = 'd9989cef9a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guksa', sa.String(length=20), nullable=True),
    sa.Column('island_name', sa.String(length=30), nullable=True),
    sa.Column('guksa_name', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=10), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('equipment_model', sa.String(length=30), nullable=False),
    sa.Column('equipment_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', 'equipment_type')
    )
    op.create_table('tbl_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_name', sa.String(length=100), nullable=True),
    sa.Column('local_guksa_name', sa.String(length=30), nullable=True),
    sa.Column('remote_guksa_name', sa.String(length=30), nullable=True),
    sa.Column('local_equip_id', sa.String(length=300), nullable=True),
    sa.Column('remote_equip_id', sa.String(length=100), nullable=False),
    sa.Column('updown_type', sa.String(length=100), nullable=False),
    sa.Column('link_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_sub_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_link_name', sa.String(length=100), nullable=True),
    sa.Column('local_guksa_name', sa.String(length=30), nullable=True),
    sa.Column('local_equip_id', sa.String(length=300), nullable=True),
    sa.Column('remote_equip_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_sub_link')
    op.drop_table('tbl_link')
    op.drop_table('tbl_equipment')
    # ### end Alembic commands ###
