"""Initial migration

Revision ID: 799a42b8b6d2
Revises: 
Create Date: 2025-04-24 16:32:36.620975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799a42b8b6d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_alarm_all',
    sa.Column('guksa_id', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=30), nullable=False),
    sa.Column('occur_datetime', sa.String(length=20), nullable=False),
    sa.Column('alarm_grade', sa.String(length=10), nullable=False),
    sa.Column('alarm_syslog_code', sa.String(length=50), nullable=False),
    sa.Column('equip_type', sa.String(length=30), nullable=False),
    sa.Column('equip_kind', sa.String(length=30), nullable=False),
    sa.Column('equip_id', sa.String(length=30), nullable=False),
    sa.Column('equip_name', sa.String(length=100), nullable=False),
    sa.Column('fault_reason', sa.String(length=100), nullable=False),
    sa.Column('valid_yn', sa.String(length=1), nullable=False),
    sa.Column('alarm_message', sa.Text(), nullable=False),
    sa.Column('insert_datetime', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('guksa_id', 'sector', 'occur_datetime', 'alarm_syslog_code', 'equip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_alarm_all')
    # ### end Alembic commands ###
