"""영향 회선

Revision ID: 4836054e0b96
Revises: 2539545074dc
Create Date: 2025-04-25 19:16:12.646114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4836054e0b96'
down_revision = '2539545074dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_EFFECTED_LINE_INFO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mgm_guksa_name', sa.String(length=30), nullable=False),
    sa.Column('guksa_gubun', sa.String(length=20), nullable=False),
    sa.Column('guksa_name', sa.String(length=30), nullable=False),
    sa.Column('facility_count', sa.Integer(), nullable=False),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('service_count', sa.Integer(), nullable=False),
    sa.Column('facility_count_sum', sa.Integer(), nullable=False),
    sa.Column('ip_access_customer_network_count', sa.Integer(), nullable=False),
    sa.Column('ip_access_count', sa.Integer(), nullable=False),
    sa.Column('ip_access_metro_customer_network_count', sa.Integer(), nullable=False),
    sa.Column('ip_core_kornet_count', sa.Integer(), nullable=False),
    sa.Column('ip_core_metro_ethernet_count', sa.Integer(), nullable=False),
    sa.Column('ip_core_premium_count', sa.Integer(), nullable=False),
    sa.Column('ip_core_vpn_count', sa.Integer(), nullable=False),
    sa.Column('transmit_customer_count', sa.Integer(), nullable=False),
    sa.Column('transmit_local_count', sa.Integer(), nullable=False),
    sa.Column('transmit_outside_count', sa.Integer(), nullable=False),
    sa.Column('exchange_network_count', sa.Integer(), nullable=False),
    sa.Column('exchange_network_bcn_count', sa.Integer(), nullable=False),
    sa.Column('wireless_network_count', sa.Integer(), nullable=False),
    sa.Column('etc_count', sa.Integer(), nullable=False),
    sa.Column('customer_count_sum', sa.Integer(), nullable=False),
    sa.Column('customer_type_private_count', sa.Integer(), nullable=False),
    sa.Column('customer_type_provider_count', sa.Integer(), nullable=False),
    sa.Column('customer_type_group_count', sa.Integer(), nullable=False),
    sa.Column('customer_type_gov_office_count', sa.Integer(), nullable=False),
    sa.Column('customer_type_kt_count', sa.Integer(), nullable=False),
    sa.Column('customer_type_etc_count', sa.Integer(), nullable=False),
    sa.Column('mgm_type_am_count', sa.Integer(), nullable=False),
    sa.Column('mgm_type_core_count', sa.Integer(), nullable=False),
    sa.Column('mgm_type_small_provider_count', sa.Integer(), nullable=False),
    sa.Column('service_count_sum', sa.Integer(), nullable=False),
    sa.Column('line_small_sum', sa.Integer(), nullable=False),
    sa.Column('line_leased_line_count', sa.Integer(), nullable=False),
    sa.Column('line_internet_count', sa.Integer(), nullable=False),
    sa.Column('line_general_phone_count', sa.Integer(), nullable=False),
    sa.Column('service_small_sum', sa.Integer(), nullable=False),
    sa.Column('service_kornet_count', sa.Integer(), nullable=False),
    sa.Column('service_vpn_count', sa.Integer(), nullable=False),
    sa.Column('service_video_secure_count', sa.Integer(), nullable=False),
    sa.Column('service_gov_info_comm_network_count', sa.Integer(), nullable=False),
    sa.Column('service_tv_count', sa.Integer(), nullable=False),
    sa.Column('service_internet_phone_count', sa.Integer(), nullable=False),
    sa.Column('insert_datetime', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', 'guksa_name')
    )
    with op.batch_alter_table('TBL_EFFECTED_LINE_INFO', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_TBL_EFFECTED_LINE_INFO_guksa_gubun'), ['guksa_gubun'], unique=False)
        batch_op.create_index(batch_op.f('ix_TBL_EFFECTED_LINE_INFO_insert_datetime'), ['insert_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_TBL_EFFECTED_LINE_INFO_mgm_guksa_name'), ['mgm_guksa_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TBL_EFFECTED_LINE_INFO', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TBL_EFFECTED_LINE_INFO_mgm_guksa_name'))
        batch_op.drop_index(batch_op.f('ix_TBL_EFFECTED_LINE_INFO_insert_datetime'))
        batch_op.drop_index(batch_op.f('ix_TBL_EFFECTED_LINE_INFO_guksa_gubun'))

    op.drop_table('TBL_EFFECTED_LINE_INFO')
    # ### end Alembic commands ###
