"""Initial migration2

Revision ID: d9989cef9a4f
Revises: 799a42b8b6d2
Create Date: 2025-04-24 16:34:00.452652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9989cef9a4f'
down_revision = '799a42b8b6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_alarm_all_last',
    sa.Column('guksa_id', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=30), nullable=False),
    sa.Column('occur_datetime', sa.String(length=20), nullable=False),
    sa.Column('alarm_grade', sa.String(length=10), nullable=False),
    sa.Column('alarm_syslog_code', sa.String(length=50), nullable=False),
    sa.Column('equip_type', sa.String(length=30), nullable=False),
    sa.Column('equip_kind', sa.String(length=30), nullable=False),
    sa.Column('equip_id', sa.String(length=30), nullable=False),
    sa.Column('equip_name', sa.String(length=100), nullable=False),
    sa.Column('fault_reason', sa.String(length=100), nullable=False),
    sa.Column('valid_yn', sa.String(length=1), nullable=False),
    sa.Column('alarm_message', sa.Text(), nullable=False),
    sa.Column('insert_datetime', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('guksa_id', 'sector', 'alarm_syslog_code', 'equip_id')
    )
    op.create_table('tbl_dr_cable_alarm_info',
    sa.Column('guksa_id', sa.String(length=3), nullable=False),
    sa.Column('selection', sa.String(length=1), nullable=False),
    sa.Column('situation_propaganda', sa.String(length=10), nullable=False),
    sa.Column('work_yn', sa.String(length=10), nullable=False),
    sa.Column('merge_yn', sa.String(length=10), nullable=False),
    sa.Column('tt_no', sa.String(length=30), nullable=False),
    sa.Column('bonbu_name', sa.String(length=30), nullable=False),
    sa.Column('center_name', sa.String(length=30), nullable=False),
    sa.Column('buseo_name', sa.String(length=30), nullable=False),
    sa.Column('op_team_name_1', sa.String(length=30), nullable=False),
    sa.Column('op_team_name_2', sa.String(length=30), nullable=False),
    sa.Column('guksa_name', sa.String(length=30), nullable=False),
    sa.Column('tt_occur_datetime', sa.String(length=20), nullable=False),
    sa.Column('alarm_occur_datetime', sa.String(length=20), nullable=False),
    sa.Column('alarm_recover_datetime', sa.String(length=20), nullable=False),
    sa.Column('continue_time', sa.String(length=20), nullable=False),
    sa.Column('effected_facility', sa.String(length=300), nullable=False),
    sa.Column('customer_count', sa.String(length=10), nullable=False),
    sa.Column('voc_count', sa.String(length=10), nullable=False),
    sa.Column('cable_name_core', sa.String(length=300), nullable=False),
    sa.Column('fault_sector', sa.String(length=300), nullable=False),
    sa.Column('sector_analysis', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fault_grade', sa.String(length=10), nullable=False),
    sa.Column('insert_datetime', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('tt_no')
    )
    op.create_table('tbl_guksa',
    sa.Column('guksa_t', sa.String(length=100), nullable=False),
    sa.Column('guksa_e', sa.String(length=100), nullable=False),
    sa.Column('guksa', sa.String(length=100), nullable=False),
    sa.Column('guksa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('guksa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_guksa')
    op.drop_table('tbl_dr_cable_alarm_info')
    op.drop_table('tbl_alarm_all_last')
    # ### end Alembic commands ###
